apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d32cc3v04-go 
  janus-idp.io/tekton: d32cc3v04-go
  backstage.io/kubernetes-id: d32cc3v04-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d32cc3v04-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml